### ISSUE TITLE
Conduits can't transfer from EnderIO capacitor bank to machines with fluxed conduits(bug?)

### ISSUE THREAD

**Issue by KristjanKr** [modmuss50/Fluxed-Redstone#14]
Using EnderIO: EnderIO-1.9.4-3.0.0.38_alpha.jar
Fluxed-Redstone:  
FluxedRedstone-2.2.1.44.jar

Expected: Transfer power from capacitor bank to the machines via fluxed conduits.
What happend: No power transfered.

http://imgur.com/r8vzeA1

**Comment by modmuss50** [comment]
That is a bug, I have not tested them with ender io just yet in 1.9.4.

**Comment by Keridos** [comment]
You probably need to have the cable networks have an energy storage capacity, similar to the old Flux Ducts and EnderIO conduits. And I am as well pretty sure that both of the RF pipes I mentioned use an abstract network run by a tickHandler to distribute energy.

**Comment by modmuss50** [comment]
Should be fixed with Forge energy support

**Comment by Morpheus1101** [comment]
This is still occuring:

Using EnderIO: EnderIO-1.10.2-3.0.1.138
Fluxed-Redstone:
FluxedRedstone-2.5.0.51

![2016-12-07_17 31 03](https://cloud.githubusercontent.com/assets/10524952/20958751/f54159be-bca2-11e6-9cdd-546f93270eaa.png)

**Comment by modmuss50** [comment]
Ok, I will take a look

**Comment by modmuss50** [comment]
Should be a lot better in the next version, let me know if its still an issue.

**Comment by Morpheus1101** [comment]
Are there meant to be updates to 1.10.2? As i only see 1.11//1.11.2

**Comment by modmuss50** [comment]
Nope, I'm done with 1.10 with this mod sorry.

**Comment by Morpheus1101** [comment]
Once EnderIO an DE r out for 1.11.2 i'll try an remember to re-test this issue
