### ISSUE TITLE
power not going through rftools and futurepack

### ISSUE THREAD

**Issue by LocoMinerDad** [modmuss50/Fluxed-Redstone#31]
I have the same issue, Plus it is doing the same thing with future pack with its neon engine. I think it is this mod if its happening over multiple mods

I seen others report this as far back as december. are you not supporting this mod anymore?

**Comment by modmuss50** [comment]
Should now be fixed.

**Comment by LocoMinerDad** [comment]
hi there, it's still not fixed. I connected a neon engine to your blaze cable and attached a rftools battery cell to the other side and it's getting zero power.
